
DROP TABLE IF EXISTS dispatch;
DROP TABLE IF EXISTS achats;
DROP TABLE IF EXISTS conf_frais_achat;
DROP TABLE IF EXISTS dons;
DROP TABLE IF EXISTS besoins;
DROP TABLE IF EXISTS produits;
DROP TABLE IF EXISTS categorie_produits;
DROP TABLE IF EXISTS villes;
DROP TABLE IF EXISTS regions;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS type_user;
